server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: "postgres"
  port: 5432
  name: "envmanager_dev"
  user: "envmanager"
  password: "1234"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: "5m"

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

security:
  encryption_key: "dev-32-byte-key-for-encryption-12"  # Must be 32 bytes for AES-256
  jwt_secret: "dev-jwt-secret-key-change-in-production"
  api_key_prefix: "em_dev_"
  bcrypt_cost: 10

logging:
  level: "debug"
  format: "console"  # console or json
  output: "stdout"   # stdout, stderr, or file path

rate_limiting:
  enabled: true
  requests_per_minute: 100
  burst: 20

cors:
  enabled: true
  allowed_origins: ["http://localhost:3000", "http://localhost:8080"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
  allowed_headers: ["*"]
  allow_credentials: true

features:
  audit_logs: true
  env_versioning: true
  backup_retention_days: 30